image:
  pullPolicy: IfNotPresent
  tag: docker.dictummortuum.com/github.com/dictummortuum/servus-extapi/cmd/servus-extapi@sha256:2b7c1caa87825e959159f9a393adce18e62d9075f6295b4b5b00cea51a01937f
imagePullSecrets: []

---
